image: $CI_REGISTRY/r3/docker/julia-custom

stages:
  - test
  - check
  - deploy-doc

test:
  stage: test

  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = true)"

  after_script:
    - julia --project=test/coverage test/coverage/coverage-summary.jl

format:
  stage: check

  script:
    - julia -e 'using JuliaFormatter; format(".", verbose=true)'

  after_script:
    - julia -e '
          out = Cmd(`git diff --name-only`) |> read |> String
          if out == ""
              exit(0)
          else
              @error "Some files have not been formatted !!!"
              write(stdout, out)
              exit(1)
          end'

pages:
  stage: deploy-doc
  script:
    - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    - julia --project=docs --color=yes docs/make.jl
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

