name: Build apptainer image

on:
  push:
    branches:
      - mk-singularity

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/singularity/singularity:v3.9.4
      options: --privileged --entrypoint /bin/sh
    steps:
    - name: check out code
      uses: actions/checkout@v1

    - name: build .sif file
      run: |
        alias apptainer=singularity
        apptainer build cobrexa.sif cobrexa.def

    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: COBREXA.jl apptainer
        path: cobrexa.sif
