name: Build and publish apptainer image

on:
  push:
    branches:
      - mk-singularity

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: sysmso/singularity-ci
      options: --privileged
    steps:
    - name: check out code
      uses: actions/checkout@v1

    - name: build .sif file
      run: |
        alias apptainer=singularity
        apptainer build cobrexa.sif cobrexa.def

    - name: push to registry
      env:
        SYLABS_IO_TOKEN: ${{ secrets.SYLABS_IO_TOKEN }}
      run: |
        alias apptainer=singularity
        echo "$SREGISTRY_TOKEN" > apptainer-token
        apptainer remote login --tokenfile apptainer-token
        apptainer push cobrexa.sif library://cylon-x/lcsb-biocore/cobrexa:latest
