name: Build and publish apptainer image

on:
  push:
    branches:
      - mk-singularity

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/singularity/singularity:v3.9.4
      options: --privileged --entrypoint /bin/sh
    steps:
    - name: check out code
      uses: actions/checkout@v1

    - name: build .sif file
      run: |
        alias apptainer=singularity
        apptainer build cobrexa.sif cobrexa.def

    - name: login to registry
      env:
        REGISTRY_TOKEN: ${{ secrets.SYLABS_IO_TOKEN }}
      run: |
        alias apptainer=singularity
        echo "$SREGISTRY_TOKEN" > .apptainer-token
        apptainer remote login --tokenfile .apptainer-token
        rm .apptainer-token

    - name: push to registry
      run: |
        alias apptainer=singularity
        apptainer push cobrexa.sif library://cylon-x/lcsb-biocore/cobrexa:latest
