name: CI
on:
  push:
    branches:
      - master
    tags: '*'
jobs:
  test:
    name: docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to LCSB R3 Gitlab Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.docker_registry }}
          username: cylon-x
          password: ${{ secrets.docker_pwd }}
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-runtest@v1
        with:
          force_latest_compatible_version: false
          coverage: false
