name: CI
on:
  push:
    branches:
      - master
    tags: '*'
jobs:
  test:
    name: run tests on github CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          username: cylon-x
          password: ${{ secrets.gitlab_access_token }}
          registry: ${{ secrets.docker_registry }}
          image: ${{ secrets.docker_img }}
          options: -v ${{ github.workspace }}:/pkg
          run: julia --check-bounds=yes --inline=yes --project=/pkg -e "import Pkg; Pkg.test();"
