name: Publish Docker image

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - develop
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: "ubuntu-20.04"
    steps:
      - name: Decapitalize the repo name
        run: |
          echo "DOCKER_IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out the repo of ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_IO_USER }}
          password: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKER_IO_USER }}/cobrexa.jl:latest"
          labels: ${{ steps.meta.outputs.labels }}

      - name: Log in to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
