name: Publish Docker image

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - master
      - develop
      - mk-singularity

jobs:
  push_to_registry:
    #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Push Docker image to GitHub Packages
    runs-on: "ubuntu-20.04"
    steps:
      - name: Decapitalize the repo name
        run: |
          echo "DOCKER_IMAGE_NAME=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Check out the repo of ${{ github.repository }}
        uses: actions/checkout@v2

      - name: Build and publish ${{ env.DOCKER_IMAGE_NAME }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ env.DOCKER_IMAGE_NAME }}
